CREATE DATABASE SNAKE_LEGO_DB;

--1.
CREATE STAGE _SNAKE_GLOBAL_TOOLS.STAGES.STG_LEGO
FILE_FORMAT = _SNAKE_GLOBAL_TOOLS.STAGES.CSV_FORMAT;


--2.
CREATE SCHEMA SNAKE_LEGO_DB.RAW_DATA;

CREATE TEMPORARY TABLE SNAKE_LEGO_DB.RAW_DATA.COLORS (
    ID NUMBER NOT NULL,
    NAME STRING NOT NULL,
    RGB STRING NOT NULL,
    IS_TRANS CHAR NOT NULL
);


COPY INTO SNAKE_LEGO_DB.RAW_DATA.COLORS
FROM @_SNAKE_GLOBAL_TOOLS.STAGES.STG_LEGO/colors.csv;


-- 3.
CREATE SCHEMA SNAKE_LEGO_DB.TRANS_ITEMS;

CREATE TABLE SNAKE_LEGO_DB.TRANS_ITEMS.TRANS_COLORS (
    ID NUMBER NOT NULL,
    NAME STRING NOT NULL,
    RGB STRING NOT NULL
);

SELECT COUNT(*) FROM SNAKE_LEGO_DB.RAW_DATA.COLORS
WHERE IS_TRANS LIKE '%t%';LIMIT ;

INSERT INTO SNAKE_LEGO_DB.TRANS_ITEMS.TRANS_COLORS(ID, NAME, RGB)
SELECT ID, NAME, RGB FROM SNAKE_LEGO_DB.RAW_DATA.COLORS
WHERE IS_TRANS LIKE '%t%';


-- 4.
CREATE SCHEMA SNAKE_LEGO_DB.TOP_THEMES;

CREATE TABLE SNAKE_LEGO_DB.TOP_THEMES.TOP_THEMES_THIS_MONTH (
    THEME STRING NOT NULL,
    COUNT NUMBER NOT NULL
);

SELECT $2, COUNT($2) FROM @_SNAKE_GLOBAL_TOOLS.STAGES.STG_LEGO/themes.csv
WHERE $2 LIKE 'Star Wars'
GROUP BY $2;

INSERT INTO SNAKE_LEGO_DB.TOP_THEMES.TOP_THEMES_THIS_MONTH (THEME, COUNT)
SELECT $2, COUNT($2) FROM @_SNAKE_GLOBAL_TOOLS.STAGES.STG_LEGO/themes.csv
WHERE $2 LIKE 'Star Wars'
GROUP BY $2;

SELECT * FROM SNAKE_LEGO_DB.TOP_THEMES.TOP_THEMES_THIS_MONTH;

